# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7facfce937399db6772670c088ca2606d29278a91a77aed651c338270b498f94c3eb447d27128c39386421abc97da86cdafe0756ce88ecf71a0baa8b8dfbabbb

test:
  secret_key_base: f49b86aec0bb3147cb592c3cc40348c0018855fa8c0ea95e376531d30d401a98e4bcfffe20750473647fdadde13be36d9d88b622e7673da480f3780301671d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
